version: 1.13.0.{build}
pull_requests:
  do_not_increment_build_number: true
shallow_clone: true
environment:
  lsltag: 1.13.0-b12
  lslversion: 1.13.0
  LSLDIST_URL: "https://github.com/sccn/liblsl/releases/download"
  CMakeArgs: ""
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      QTCOMPILER: msvc2017_64
      QTVER: 5.13
install:
- cmd: appveyor DownloadFile https://github.com/ninja-build/ninja/releases/download/v1.9.0/ninja-win.zip -FileName ninja.zip
- cmd: appveyor DownloadFile %LSLDIST_URL%/%lsltag%/liblsl-%lslversion%-Win64.7z -FileName liblsl_x64.7z
- cmd: 7z x ninja.zip
- cmd: set PATH=%cd%;%PATH%
- cmd: 7z x liblsl_x64.7z -oLSL
- cmd: ninja --version
build_script:
- cmd: call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
- cmd: cmake -S . -B build -G Ninja -DQt5_DIR=C:/Qt/%QTVER%/%QTCOMPILER%/lib/cmake/Qt5 -DLSL_INSTALL_ROOT=LSL/ %CMakeArgs%
- cd build
- cmake --build . --config Release --target install
- cpack -C Release
artifacts:
- path: 'build/*.7z'
