version: 1.0.{build}
environment:
  lsltag: 1.13.1
  lslversion: 1.13.1
  LSLDIST_URL: '"https://github.com/sccn/liblsl/releases/download"'
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    QTCOMPILER: msvc2019_64
    QTVER: 5.15.0
install:
- cmd: >-
    appveyor DownloadFile %LSLDIST_URL%/%lsltag%/liblsl-%lslversion%-Win64.zip -FileName liblsl_x64.zip

    7z x liblsl_x64.zip -oLSL
build_script:
- cmd: >-
    cmake -S . -B build -DQt5_DIR=C:/Qt/%QTVER%/%QTCOMPILER%/lib/cmake/Qt5 -Dlsl_DIR=LSL/share/LSL/ %CMakeArgs% -A x64

    cmake --build build --config Release -j --target BrainAmpSeries